"""Supabase integration layer for live database synchronization.

Supports syncing companies, founders, leads, campaigns, and sends
from SQLite to Supabase PostgreSQL in real-time.
"""

from __future__ import annotations

import logging
import os
from typing import Optional

from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)


def is_configured() -> bool:
    """Check if Supabase credentials are in environment."""
    url = os.getenv("SUPABASE_URL", "").strip()
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "").strip() or os.getenv("SUPABASE_KEY", "").strip()
    return bool(url and key)


def get_supabase_client():
    """Return an authenticated Supabase client."""
    from supabase import create_client

    url = os.getenv("SUPABASE_URL", "").strip()
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "").strip() or os.getenv("SUPABASE_KEY", "").strip()

    if not url or not key:
        raise RuntimeError(
            "SUPABASE_URL and SUPABASE_KEY (or SUPABASE_SERVICE_ROLE_KEY) must be set in your .env file."
        )

    return create_client(url, key)



# SQL DDL script to create tables in Supabase SQL Editor if needed
SUPABASE_SQL_SCHEMA = """
-- Run this in Supabase SQL Editor:

CREATE TABLE IF NOT EXISTS companies (
    id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                    TEXT NOT NULL,
    website                 TEXT,
    domain                  TEXT UNIQUE,
    sector                  TEXT,
    description             TEXT,
    location                TEXT,
    work_mode               TEXT,
    employee_count          INT,
    employee_count_confidence TEXT,
    funding_status          TEXT,
    funding_details         TEXT,
    funding_source_url      TEXT,
    founder_quality_score   FLOAT,
    company_potential_score FLOAT,
    sector_fit_score        FLOAT,
    funding_traction_score  FLOAT,
    total_fit_score         FLOAT,
    classification          TEXT DEFAULT 'DISCOVERED',
    rationale               TEXT,
    researched_at           TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS founders (
    id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    full_name               TEXT NOT NULL,
    title                   TEXT,
    university              TEXT,
    previous_companies      TEXT,
    founder_quality_evidence TEXT,
    profile_url             TEXT,
    source_urls_json        JSONB
);

CREATE TABLE IF NOT EXISTS leads (
    id                             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                     BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    full_name                      TEXT NOT NULL,
    first_name                     TEXT NOT NULL,
    title                          TEXT,
    contact_priority               TEXT,
    profile_url                    TEXT,
    honorific                      TEXT,
    honorific_confidence           TEXT,
    honorific_evidence_url         TEXT,
    email                          TEXT UNIQUE,
    email_provider                 TEXT,
    email_score                    FLOAT,
    email_verification_status      TEXT,
    email_source_urls_json         JSONB,
    personalization_paragraph      TEXT,
    personalization_source_urls_json JSONB,
    subject                        TEXT,
    rendered_body                  TEXT,
    attachment_path                TEXT,
    eligibility                    INT DEFAULT 0,
    status                         TEXT DEFAULT 'CONTACT_FOUND',
    created_at                     TIMESTAMPTZ,
    updated_at                     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS campaigns (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            TEXT NOT NULL,
    target_leads    INT DEFAULT 100,
    snapshot_hash   TEXT,
    approved        INT DEFAULT 0,
    approved_at     TIMESTAMPTZ,
    scheduled_start TIMESTAMPTZ,
    timezone        TEXT DEFAULT 'Europe/Istanbul',
    status          TEXT DEFAULT 'BUILDING'
);

CREATE TABLE IF NOT EXISTS sends (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_id     BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    lead_id         BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    scheduled_at    TIMESTAMPTZ,
    attempted_at    TIMESTAMPTZ,
    sent_at         TIMESTAMPTZ,
    gmail_message_id TEXT,
    error_code      TEXT,
    error_message   TEXT
);

-- Disable Row Level Security (RLS) for direct script access (or use service_role key):
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE founders DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE sends DISABLE ROW LEVEL SECURITY;

"""
